#!/bin/sh
# Pin and verify an upstream release before applying ChopChop's sandbox signature.
set -eu
if [ "$#" != 1 ] || ! printf '%s\n' "$1" | /usr/bin/grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo 'Usage: Scripts/update-aria2-next.sh VERSION' >&2
    exit 2
fi
version="$1"
repo_root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
vendor="$repo_root/Vendor/Aria2Next"
staging="$(/usr/bin/mktemp -d)"
trap '/bin/rm -rf "$staging"' EXIT HUP INT TERM
asset="aria2-next-$version-macos-arm64"
release="https://github.com/AnInsomniacy/aria2-next/releases/download/v$version"
/usr/bin/curl -fLSs --retry 2 "$release/$asset" -o "$staging/$asset"
/usr/bin/curl -fLSs --retry 2 "$release/aria2-next-$version-checksums.sha256" -o "$staging/checksums"
upstream_sha="$(/usr/bin/awk -v name="$asset" '$2 == name {print $1}' "$staging/checksums")"
if ! printf '%s\n' "$upstream_sha" | /usr/bin/grep -Eq '^[0-9a-f]{64}$'; then
    echo 'error: Missing or ambiguous upstream checksum.' >&2
    exit 1
fi
actual_sha="$(/usr/bin/shasum -a 256 "$staging/$asset" | /usr/bin/awk '{print $1}')"
if [ "$actual_sha" != "$upstream_sha" ]; then
    echo 'error: Upstream SHA-256 verification failed.' >&2
    exit 1
fi
/bin/mv "$staging/$asset" "$staging/aria2-next"
/bin/chmod 755 "$staging/aria2-next"
/usr/bin/curl -fLSs --retry 2 "https://raw.githubusercontent.com/AnInsomniacy/aria2-next/v$version/COPYING" -o "$staging/Aria2Next-COPYING.txt"
/usr/bin/codesign --force --sign - --timestamp=none --options runtime \
    --identifier com.conight.ChopChop.aria2-next \
    --entitlements "$vendor/Aria2Next.entitlements" "$staging/aria2-next"
bundled_sha="$(/usr/bin/shasum -a 256 "$staging/aria2-next" | /usr/bin/awk '{print $1}')"
source_url="https://github.com/AnInsomniacy/aria2-next/archive/refs/tags/v$version.tar.gz"
/usr/bin/curl -fLSs --retry 2 "$source_url" -o "$staging/source.tar.gz"
source_sha="$(/usr/bin/shasum -a 256 "$staging/source.tar.gz" | /usr/bin/awk '{print $1}')"
"$repo_root/Scripts/validate-aria2-next.sh" "$staging/aria2-next" "$version" "$bundled_sha"
cat > "$staging/Aria2Next.xcconfig" <<EOF
// Generated by Scripts/update-aria2-next.sh. Shared by the app and tests.
ARIA2_NEXT_VERSION = $version
ARIA2_NEXT_UPSTREAM_SHA256 = $upstream_sha
ARIA2_NEXT_BUNDLED_SHA256 = $bundled_sha
ARIA2_NEXT_SOURCE_SHA256 = $source_sha
EOF
cat > "$staging/Aria2Next-NOTICE.txt" <<EOF
Aria2 Next $version
Copyright (C) the aria2 and Aria2 Next contributors

Source: https://github.com/AnInsomniacy/aria2-next/tree/v$version
Source archive: https://github.com/AnInsomniacy/aria2-next/archive/refs/tags/v$version.tar.gz
Release: https://github.com/AnInsomniacy/aria2-next/releases/tag/v$version
License: GNU General Public License, version 2 or later
Upstream arm64 SHA-256: $upstream_sha
Bundled arm64 SHA-256: $bundled_sha

The macOS arm64 release executable is embedded as a separately executed
helper tool. Its code signature is replaced with an ad-hoc signature with
ChopChop's sandbox inheritance entitlements; executable code is unchanged.
See Aria2Next-COPYING.txt for the license text and upstream source for
the engine's bundled libraries and their notices.
EOF
for file in aria2-next Aria2Next-COPYING.txt Aria2Next-NOTICE.txt Aria2Next.xcconfig; do
    /bin/cp "$staging/$file" "$vendor/$file"
done
echo "Updated Aria2 Next to $version. Run Scripts/check.sh all before shipping."
